export const storeProducts = [
{
    id: 1,
    title: 'Aloo Paratha',
    img: "images/alooParatha.jpg",
    price: 100,
    company: "Samsung",
    time: '20-25 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 2,
    title: 'Aloo Tikki',
    img: "images/alooTikki.jpg",
    price: 55,
    company: "Asus",
    time: '10-15 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 3,
    title: 'Bread Pakoda',
    img: "images/breadPakoda.jpg",
    price: 120,
    company: "Samsung",
    time: '5-10 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 4,
    title: 'Chhole Bhature',
    img: "images/chholeBhature.jfif",
    price: 60,
    company: "Apple",
    time: '25-30 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 5,
    title: 'Coffee',
    img: "images/coffee.jpg",
    price: 70,
    company: "Asus",
    time: '30-40 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 6,
    title: 'Sandwich',
    img: "images/sandwich.jpg",
    price: 100,
    company: "Apple",
    time: '10-15 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 7,
    title: 'Dosa',
    img: "images/dosa.jpg",
    price: 200,
    company: "Samsung",
    time: '20-25 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 8,
    title: 'Idli',
    img: "images/idli.jpg",
    price: 150,
    company: "Huawei",
    time: '30-35 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 9,
    title: 'Tea',
    img: "images/tea.jpg",
    price: 40,
    company: "Samsung",
    time: '5-10 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 10,
    title: 'Noodles',
    img: "images/noodles.jpg",
    price: 80,
    company: "Huawei",
    time: '15-20 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 11,
    title: 'White Sauce Pasta',
    img: "images/pasta.jpg",
    price: 50,
    company: "Lenovo",
    time: '30-35 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 12,
    title: 'Patties',
    img: "images/patties.jpg",
    price: 70,
    company: "Oppo",
    time: '10-20 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 13,
    title: 'Pav Bhaji',
    img: "images/pavBhaji.jpg",
    price: 110,
    company: "Oppo",
    time: '20-25 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 14,
    title: 'Rajma Chawal',
    img: "images/rajmachawal.jpg",
    price: 70,
    company: "Lenovo",
    time: '30-40 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 15,
    title: 'Red Sauce Pasta',
    img: "images/redSaucePasta.jpg",
    price: 80,
    company: "Huawei",
    time: '20-25 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 16,
    title: 'Samosa',
    img: "images/samosa.jpg",
    price: 20,
    company: "Redmi",
    time: '10-15 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 17,
    title: 'Pizza',
    img: "images/pizza.png",
    price: 90,
    company: "Redmi",
    time: '25-30 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 18,
    title: 'Zucchini',
    img: "images/Zucchini.png",
    price: 100,
    company: "Redmi",
    time: '30-40 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 19,
    title: 'Grilled Barbecue',
    img: "images/grilledBarbecue.png",
    price: 120,
    company: "Redmi",
    time: '35-40 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 20,
    title: 'French Fries',
    img: "images/frenchFries.png",
    price: 90,
    company: "Redmi",
    time: '10-20 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 21,
    title: 'Chocolate Cake',
    img: "images/chocolateCake.png",
    price: 90,
    company: "Redmi",
    time: '25-30 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
}
];

export const detailProduct = {
    id: 1,
    title: "ABC",
    img: "images/sandwich.jpg",
    price: 10,
    company: "Google",
    time: '30-40 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum adipisci sint, animi iure amet repudiandae similique rem eveniet voluptatibus cum nostrum placeat quam nisi corrupti! Suscipit ad tempore quisquam deleniti sint adipisci voluptatum modi, excepturi saepe nulla omnis, tempora nam, delectus autem asperiores vero voluptas? At, iste laborum, maiores modi dolorum porro quisquam mollitia reprehenderit quae enim accusamus expedita obcaecati aperiam et rem atque neque quas! Maxime nihil esse tempora?",
    inCart: false,
    count: 0,
    total: 0
};

